#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;
use JSON;
use App::Depentree;

my $opt_root = '.';
my $opt_lib;
GetOptions('root=s' => \$opt_root, 'lib=s' => \$opt_lib)
  or die("Error in command line arguments\n");

my $modules = App::Depentree->new(root => $opt_root, lib => $opt_lib)->venga;

print JSON->new->canonical(1)
  ->pretty->encode(
    [ sort { $a->{module} cmp $b->{module} } map { { module => $_, version => $modules->{$_} } } keys %$modules ]);
